import { Heading } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import React from 'react';
import styles from '../styles/Home.module.css';
import { Footer } from '@/components/organisms/footer';
import { Header } from '@/components/organisms/header';
import { client } from '@/lib/client';
import generatedRSSFeed from '@/lib/feed';
import { BlogType } from '@/types/blog';

const Home: NextPage = ({ blog }: any) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />

            <main className={styles.main}>
                <Heading>ChakraUI</Heading>
                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">Next.js!</a>
                </h1>

                <p className={styles.description}>
                    Get started by editing <code className={styles.code}>pages/index.tsx</code>
                </p>

                <div className={styles.grid}>
                    <a href="https://nextjs.org/docs" className={styles.card}>
                        <h2>Documentation &rarr;</h2>
                        <p>Find in-depth information about Next.js features and API.</p>
                    </a>

                    <a href="https://nextjs.org/learn" className={styles.card}>
                        <h2>Learn &rarr;</h2>
                        <p>Learn about Next.js in an interactive course with quizzes!</p>
                    </a>

                    <a
                        href="https://github.com/vercel/next.js/tree/master/examples"
                        className={styles.card}
                    >
                        <h2>Examples &rarr;</h2>
                        <p>Discover and deploy boilerplate example Next.js projects.</p>
                    </a>

                    <a href="http://localhost:3000/blog/" className={styles.card}>
                        <h2>ブログ &rarr;</h2>
                        <p>こちらからブログを確認できます。</p>
                    </a>
                </div>
            </main>

            <Footer />
        </div>
    );
};

export const getStaticProps = async () => {
    generatedRSSFeed();
    return {
        props: {},
    };
};
export default Home;
